### ISSUE TITLE
A new release of this package

### ISSUE THREAD

**Issue by DannyFeliz** [duythien/cashier#2]
I was wondering if you could do a new release of this package because if you run 
`composer require duythien/cashier` 
composer will install the version `v1.0.0` which was released in _May 25_.

Actually I using this package as `duythien/cashier: dev-master` but as you know this is not good because if you update the package in `master` can break something in my app.

**Comment by duythien** [comment]
Hello @DannyFeliz 

I just add a new release :) you can see that at https://packagist.org/packages/duythien/cashier

**Comment by DannyFeliz** [comment]
Yep, this is what I need, thanks @duythien

**Comment by duythien** [comment]
@DannyFeliz No problem :)
